import type { PropertyListing } from './types';

export const mapListings: PropertyListing[] = [
  {
    id: '1',
    price: '₹ 95 L',
    priceUnit: '',
    type: 'Retail Shop',
    area: '850',
    areaUnit: 'sqft',
    location: 'HITEC City',
    imageUrl: '/property-images/retail-shop.png',
    markerType: 'retail',
    lat: 25,
    lng: 12,
  },
  {
    id: '2',
    price: '₹ 12 Cr',
    priceUnit: '',
    type: 'Showroom',
    area: '6000',
    areaUnit: 'sqft',
    location: 'Kukatpally',
    imageUrl: '/property-images/showroom.png',
    markerType: 'showroom',
    lat: 20,
    lng: 75,
    premium: true,
  },
  {
    id: '3',
    price: '₹ 4.2 Cr',
    priceUnit: '',
    type: 'Office Space',
    area: '3200',
    areaUnit: 'sqft',
    location: 'Madhapur',
    imageUrl: '/property-images/office-space.png',
    markerType: 'office',
    lat: 43,
    lng: 47,
    premium: true,
  },
  {
    id: '4',
    price: '₹ 2.6 Cr',
    priceUnit: '',
    type: 'Warehouse',
    area: '10000',
    areaUnit: 'sqft',
    location: 'Gachibowli',
    imageUrl: '/property-images/warehouse.png',
    markerType: 'warehouse',
    lat: 68,
    lng: 14,
  },
  {
    id: '5',
    price: '₹ 1.8 Cr',
    priceUnit: '',
    type: 'Commercial Plot',
    area: '300',
    areaUnit: 'sqyd',
    location: 'Kompally',
    imageUrl: '/property-images/commercial-plot.png',
    markerType: 'plot',
    lat: 28,
    lng: 82,
  },
];

export const mapLabels = [
  { label: 'MIYAPUR',           top: 10, left: 62 },
  { label: 'HITEC CITY',        top: 24, left: 8  },
  { label: 'KUKATPALLY',        top: 18, left: 76 },
  { label: 'GACHIBOWLI',        top: 56, left: 5  },
  { label: 'FINANCIAL DISTRICT',top: 73, left: 2  },
  { label: 'MADHAPUR',          top: 42, left: 40 },
  { label: 'JUBILEE HILLS',     top: 64, left: 46 },
  { label: 'BANJARA HILLS',     top: 79, left: 46 },
  { label: 'KOMPALLY',          top: 26, left: 86 },
  { label: 'LB NAGAR',          top: 94, left: 78 },
];
