import type { PropertyVideo, VideoCategory } from '../shared/theme/videoflow.types';

export const propertyVideos: PropertyVideo[] = [
  {
    id: 'v1',
    title: 'Grade A Office Investment in Madhapur',
    location: 'Madhapur, Hyderabad',
    thumbnail: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80',
    videoUrl: 'dQw4w9WgXcQ',
    returns: '12% IRR',
    category: 'Commercial',
    duration: '0:42',
    likes: 128,
    comments: 18,
    shares: 24,
    price: '₹5.4 Cr',
    area: '5,000 sq ft',
    tag: 'Commercial',
    isBookmarked: true,
    isLiked: true,
  },
  {
    id: 'v2',
    title: 'Chai Point Franchise Opportunity',
    location: 'Madhapur, Hyderabad',
    thumbnail: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=800&q=80',
    videoUrl: 'ScMzIvxBSi4',
    returns: '35% ROI',
    category: 'Franchise',
    duration: '0:36',
    likes: 96,
    comments: 12,
    shares: 16,
    price: '₹30 L',
    area: '800 sq ft',
    tag: 'Franchise',
    isBookmarked: false,
    isLiked: false,
  },
  {
    id: 'v3',
    title: 'Warehouse Investment in Kompally',
    location: 'Kompally, Hyderabad',
    thumbnail: 'https://images.unsplash.com/photo-1586528116311-ad8ed7c83a50?auto=format&fit=crop&w=800&q=80',
    videoUrl: '3JZ_D3ELwOQ',
    returns: '9.5% Yield',
    category: 'Pre-Leased',
    duration: '0:45',
    likes: 84,
    comments: 14,
    shares: 20,
    price: '₹12.5 Cr',
    area: '15,000 sq ft',
    tag: 'Pre-Leased',
    isBookmarked: false,
    isLiked: false,
  },
  {
    id: 'v4',
    title: 'Premium Retail Space Ownership',
    location: 'Jubilee Hills, Hyderabad',
    thumbnail: 'https://images.unsplash.com/photo-1604014237800-1c9102c219da?auto=format&fit=crop&w=800&q=80',
    videoUrl: 'oHg5SJYRHA0',
    returns: '11% IRR',
    category: 'Fractional',
    duration: '1:15',
    likes: 245,
    comments: 32,
    shares: 45,
    price: '₹25 L',
    area: 'Fractional',
    tag: 'Fractional',
    isBookmarked: false,
    isLiked: false,
  },
  {
    id: 'v5',
    title: 'K12 International School Setup',
    location: 'Gachibowli, Hyderabad',
    thumbnail: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=800&q=80',
    videoUrl: 'yPYZpwSpKmA',
    returns: '22% ROI',
    category: 'Education',
    duration: '2:10',
    likes: 412,
    comments: 55,
    shares: 89,
    price: '₹2.5 Cr',
    area: '10,000 sq ft',
    tag: 'Education',
    isBookmarked: false,
    isLiked: true,
  },
  {
    id: 'v6',
    title: 'High Street Commercial Retail',
    location: 'Banjara Hills, Hyderabad',
    thumbnail: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
    videoUrl: 'kXYiU_JCYtU',
    returns: '8.5% Yield',
    category: 'Pre-Leased',
    duration: '1:30',
    likes: 156,
    comments: 21,
    shares: 34,
    price: '₹8.2 Cr',
    area: '3,200 sq ft',
    tag: 'Pre-Leased',
    isBookmarked: true,
    isLiked: false,
  },
  {
    id: 'v7',
    title: 'QSR Master Franchise',
    location: 'HITEC City, Hyderabad',
    thumbnail: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=80',
    videoUrl: 'hT_nvWreIhg',
    returns: '40% ROI',
    category: 'Franchise',
    duration: '0:55',
    likes: 389,
    comments: 44,
    shares: 76,
    price: '₹45 L',
    area: '1,200 sq ft',
    tag: 'Franchise',
    isBookmarked: false,
    isLiked: false,
  },
  {
    id: 'v8',
    title: 'Tech Park Grade A Office',
    location: 'Financial District, Hyderabad',
    thumbnail: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80',
    videoUrl: 'ZbZSe6N_BXs',
    returns: '10% Yield',
    category: 'Commercial',
    duration: '1:45',
    likes: 567,
    comments: 67,
    shares: 112,
    price: '₹15 Cr',
    area: '12,000 sq ft',
    tag: 'Commercial',
    isBookmarked: false,
    isLiked: true,
  }
];

export const categories: VideoCategory[] = [
  'All',
  'Franchise',
  'Fractional',
  'Commercial',
  'Pre-Leased',
  'Education',
];